### ISSUE TITLE
[audit] Complete an audit of Solidity smart contracts

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1010]
### Summary
As part of ensuring our Carbonmark smart contracts of are the highest standard for security, vulnerability protection, and coding practices, it is recommended that a 3rd party audit be conducted. This process will be important in terms of making sure our users can trust the safety, security, and reliability of our blockchain application.

The 3rd party audit is not required for MVP launch but should happen shortly thereafter. An internal review (#185) will be completed before the MVP/beta launch.

**Comment by jabby09** [comment]
@sy-zygy assigned this to you so we don't forget

I had a note from a product sync meeting:

> would like look to bundle retirement bonds audit with carbonmark contracts

**Comment by sy-zygy** [comment]
We should probably assign this to @cujowolf since that action will probably should have a KIP.

This was the provider I mentioned in the past that provides insured audits which is interesting, their deck:
https://docs.google.com/presentation/d/1UUTHlTM6WLX301als7QbV8lRHTTXEViWDCOfcRDXL5Q/edit?usp=drivesdk
