### ISSUE TITLE
[performance] Convert BigNumbers further up the chain

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1013]
## Description

From a PR comment:

> Not a change request just something to keep in mind: would be nice to convert these BigNumbers further up the chain if possible, which is what I do in the app as soon as they are fetched before setting to redux state. So components only ever deal with stringified numbers.
> 
> Ideally the backend just gives us strings, we can ask them.
> 
> Unless of course we need to do actual bignumber math, in which case we need to keep them as bignumbers.

_Originally posted by @Atmosfearful in https://github.com/Atmosfearful/bezos-frontend/pull/48#discussion_r1083195081_
            

## Current state

At the moment, all pages fetch their data directly yon the server from the API.
The numbers in the API data are BigBumbers.
These are passed down to the page, which is currently converting all BigNumbers to numbers.

See all types here:
https://github.com/Atmosfearful/bezos-frontend/blob/bezos-main/lib/types/carbonmark.ts

**Comment by jabby09** [comment]
@biwano can you do a discovery / review of this one...
still an issue?
worth tackling?
how much effort?

**Comment by biwano** [comment]
Hi @jabby09 

I reviewed all the endpoints responses from the API and there seems that no big numbers are ever sent back.
Nevertheless I found another discrepancy. Everywhere timestamp are strings representing by seconds since epoch except for users where the timestamps are numbers representing milliseconds since epoch.

I will make one or multiple PRs for that depending if there are impacts on the frontend. This should take less than a day.
