### ISSUE TITLE
[stretch] Refactor & Enhancements for /retirements pages

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1018]
First we should make some enhancements to the retire flow, which are highlighted here #1096

Finally, we can do this ticket, which describes some code cleanup to simplify /retirements page rendering.

# Considerations
- Currently, we have some complex fallback logic that calls the retirement aggregator storage contract via RPC, if the subgraph data is not available. The reason this is included, is because sometimes the subgraph can be slow to index.
- Instead of complicating this page rendering, I think we should remove this extra logic and simply treat subgraph as "source of truth". _No subgraph record -> show 404._

# Requirements for Single Retirement Page (`/retirements/[address]/[index]`)
* [x] Simplify data fetching so we only use subgraph. If the retirement is not indexed in the subgraph yet, 404. The client can retry if neccesary.
* [x] This data is static so we can set revalidation time to be long if all data is present - 86400 seconds (24 hours)
  * [x] However if the data is not present and we throw 404, then set the revalidation time to be very short - 0 seconds ?
  
# Requirements for Retirements List (`/retirements/[address]`)
Take a peek at get static props and see if there are some improvements we can make.
* [x] Revalidation time should be short, so new retirements appear quickly.

**Comment by jabby09** [comment]
@Atmosfearful @0xMakka request to also add `Batch serial number` to the query, assuming that data is on the graph? @cujowolf

**Comment by psparacino** [comment]
Update after performance profiling in #918:

**SingleRetirements**:
1) for new retirements: the potential way forward is to use the approach outlined in #1096 : [approach here](https://github.com/KlimaDAO/klimadao/issues/1096#issuecomment-1613826862) to wait for the subgraph to index.

Otherwise send to 404.

2) For existing retirements: Look into cache solution for faster first load.

**Retirements List**

1. Remove RPC calls and use subgraph as single source of truth.
2. Also possible to cache/revalidate with cron job for a faster first load.
