### ISSUE TITLE
[listings] Better solution for fractional purchases and / token dust

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1035]
We can either
- Enable purchasing of fractional amounts less than 1 tonne
- or, Hide fractional amounts and stick to our 1 tonne minimum (but don't hide them in the portfolio)
- or, Enforce 1 tonne intervals universally throughout the app to reduce the occurance of token dust? i.e. make it impossible to purchase 1.1 tonnes.

**Comment by jabby09** [comment]
@Atmosfearful elevating this issue for discovery discussion as getting multiple users requests to deal with token dust in the marketplace

**Comment by Atmosfearful** [comment]
Here is an example of a project with token dust that should be hidden.

https://www.carbonmark.com/projects/VCS-1529-2012

**Comment by jabby09** [comment]
@0xemc @biwano @Atmosfearful updating this issue with latest comments in discord

What is everyone's opinion on showing projects for which there are only crumbs available for supply? Should we only be showing projects with > 1 tonne available?

Yes listings or pools with token dust <1 tonne should be hidden except for listings on a /user/ page— if we hide those listings then the user can't unlist the dust. 
Because the /user/ page is where they go to delete a listing
Triple checked with Drew and he is aligned

Imo the cutoff should be set with a global constant because in future we may need to go lower than 1 tonne if eg the tonne is $200/tonne

Tonnes, i think even with an expensive tonne, a user doing fractional offsetting via UI is exceptionally rare

I think the more likely use case of < 1 tonne is fractional offset at a transaction level (supply chain?) using the api

But I do see what Marcus is saying, if we do eventually have expensive tonnes from like CDR projects we may need to revisit this. But our most expensive project is $30 so not really a big deal at the moment.

**Comment by Atmosfearful** [comment]
Refined requirements after discussion w/ jabby:

**For /projects API endpoint and /projects page**
- Do not return a project unless it has a purchaseable quantity (listing or pool price).
- "Purchaseable quantity" means >1 tonne (listed, or pooled)

**For /projects/[:id] API endpoint and project details page**
- Always return a response, if the project has a title and id (in either our cms, or subgraph)
- Filter out any listings or prices that don't have a purchaseable quantity
- The bare minimum response may be just the project title/id/category alone-- (no prices, no listings, no supply, no description)!
Why? to eventually capture SEO for every project in the voluntary carbon market. These are only accessible if you know the URL.

**Comment by jabby09** [comment]
@biwano please see requirement clarification in the above comment
