### ISSUE TITLE
[translation] Spanish language site does not appear on google

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1051]
This may be a false alarm, but I can't seem to get spanish results to appear.

The whole point of translating the site by hand is that it appears on foreign language search engines...

I do not have any ideas at the moment...

**Comment by jabby09** [comment]
@0xtapi can you confirm if this is still an issue? If no please close.

**Comment by 0xtapi** [comment]
> @0xtapi can you confirm if this is still an issue? If no please close.

Seems to be an issue still. I cannot get German or French to work either. When I tell Google to search for specific text, like "The largest selection of digital carbon credits worldwide.", the search results return Carbonmark in English. The same phrase in its translated version in Spanish/French/German leads to no results related to Carbonmark 🤔. I didn't try any other languages because I cannot read them, but I assume it's the same issue everywhere.

Tried it with a Spanish VPN as well. Doesn't seem to make a difference. Can't make any language other than English appear.
