### ISSUE TITLE
[retirements] Check for fresh retirement data before navigating to retirement page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1096]
Prerequisite for #1080 
Currently, in our retirement pages, we have some complex fallback logic and loading spinners, because the subgraph can be slow. The goal is to get these removed and simplified in #1018 

In order to accomplish this, we must first make some changes at the end of the retirement flows.

### Context
At the end of a retirement, we will show a receipt page

* [x] On the receipt page, which is We should poll the subgraph to wait for a retirement record to be indexed and appear in subgraph before we navigate to this page, that way the user should never encounter a 404.

**Comment by psparacino** [comment]
Based off the performance profiling, the fallback rpc calls are redundant and slowing down the page load. All the necessary data is available from the subgraph, which has a consistently faster response time.  In order to ensure the subgraph has indexed and has the data:

- [ ] Retrieve block number from the transaction receipt
- [ ] Poll the subgraph for current block number being indexed (`_meta`)
- [ ] If the block has been reached, then query the subgraph, retrieve data, and router.push to retirement page

pseudo-code version:
```
const navigateToRetirement = async () => {
		const [blockNumber] = getBlockFromReceipt(txn);
		await pollSubgraphBlock({ until: blockNumber });
		router.push(`/retirements/${beneficiaryAddr}/${retirementIndex}`);
}
```

- [ ] can also attempt to implement the same above functionality simply using a while loop and a counter to abort after a certain number of tries.

**Comment by Atmosfearful** [comment]
More thoughts on the UX for navigating to a retirement page after completing a retirement txn. Slight deviation from my pseudocode above.

- After retirement succeeds, show the success state, in place of the link/button, show a spinner or a 'generating retirement page' state of some kind
- As soon as the poller succeeds, we can use ```router.prefetch(`/retirements/${beneficiaryAddr}/${retirementIndex}`)``` to trigger the server side page generation
- Then we can set `pending` to false, and render the button, just a simple link-button
- Link should have `target="_blank"` to open in new tab
