### ISSUE TITLE
[credit card journey] Pool / seller listing design flows to pay with credit card

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1233]
Need to have figma updated to show the full user journey flow for credit card.

Credit card as a payment method is supported for RETIRE of a pool or seller listing. 

- [x] The user journey would start by selecting Credit Card from the Pay with: dropdown. The design should show this option activated (not coming soon anymore)
<img width="522" alt="Screenshot 2023-06-22 at 9 58 32 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/7f001f25-3748-4a19-ac0a-4c81778aa5eb">

- [x] When credit card is selected, will want to update the icon on the form from USDC symbol to whatever icon we are using for Credit Card.

- [x] When credit card is selected, we need to indicate on the Total cost that the maximum allowed is $2000. Example below from the retirement aggregator:
<img width="402" alt="Screenshot 2023-06-22 at 10 04 35 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/50261def-2843-426a-93f6-31e3c264ce6b">

- [x] On the strip checkout screen, need to swap out the Klima Infinity logo for a Carbonmark logo.
<img width="986" alt="Screenshot 2023-06-22 at 10 16 05 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ce1f0472-32e8-44a9-ba07-4aa2b4b16e6b">

- [x] Next, on the Transaction complete screen, need to update Klima references again. 

- Return to klimadao.finance should be carbonmark.com/projects
- swap out the Klima Infinity logo for a Carbonmark logo

<img width="649" alt="Screenshot 2023-06-22 at 10 20 43 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/a65fd942-6b3b-493f-944b-43615f9933ee">

**Comment by theprofessora** [comment]
Here are the updated wireframes: https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F?node-id=890:29468&mode=design#480130483

Please note the following

1. I don't have access to the stripe account so I can't change the assets mentioned on the checkout screen or the transaction complete screen, that will have to be @Atmosfearful 

2. we must update the help text under the "pay with" dropdown. the text is reflected in the wireframes.

3.  we cannot process credit card payments exceeding $2,000, so there's a new use case in the user journey that displays this possible error state.

4. the dynamic price cards will have to change to show new units. instead of the usdc icon, we'll need to insert dollar signs. the wireframes show this change.

5. the approve modal changes to notify the user of our third party payment provider.

**Comment by jabby09** [comment]
> * I don't have access to the stripe account so I can't change the assets mentioned on the checkout screen or the transaction complete screen, that will have to be @Atmosfearful
> *

@theprofessora yup, understood that atmos will need to change those but is it still possible to mock those up using a screen shot current and swapping out the images?

This will be helpful as a design reference for the dev but also Liam is looking for design screen shots for his sales pitch deck

**Comment by theprofessora** [comment]
done
