### ISSUE TITLE
[credit card] Retirement receipt pages are showing 404

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1322]
@ladytrekker I found an issue this morning with CC payments and the retirement receipts. I will create a ticket but wanted to capture here as well. The bug happens on staging and production.

To replicate:

1. Retire any project and pay with credit card
2. On the transaction complete page, hover on view proof of retirement link and you can see in this example this was the 28th retirement on this wallet (which is correct) - 1st screenshot
3. Clicking on link gives 404 page - 2nd screenshot
4. On retirements summary page for this wallet, number of retirements is correct, however, individual credit card retirements are not appearing. The last one showing on June 30 is retirement 23 - 3rd screenshot
5. Same retire on /retire page - 4th screenshot
6. I'm pretty sure retirements 24-28 were all credit card ones I have done as part of testing the feature
7. wallet is 0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483

![image](https://github.com/KlimaDAO/klimadao/assets/103535195/ba152cfe-d2fc-441b-81d1-504bad7922e2)
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/9eb51b73-2cb5-4f4f-9781-54bfdf37d959)
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/713f42a8-dfdd-481e-ae15-cca51ac18253)
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/2c47fb94-8cb5-42ea-926f-1e1272710007)

**Comment by jabby09** [comment]
cc @Atmosfearful

**Comment by ladytrekker** [comment]
## Data sources

The Totals Sidebar from your screenshot is retrieving your data via the RetirementAggregatorV2.

**Get **total number of retirements** from Jabby**
- => Pseudo Code: `retirementAggregatorV2.getTotalRetirements(0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483)`
- See actual code in [Klimadao/lib](https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/getTotalRetirements/index.ts)
- => Number includes all retirements **INCLUDING** the ones with credit card ✅ 

**Get total carbons retired for Jabby**
- => Pseudo Code: `retirementAggregatorV2.getTotalCarbonRetired(0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483)`
- See actual code in [Klimadao/lib](https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/getTotalCarbonRetired/index.ts)
- => Number includes all retirements **INCLUDING** the ones with credit card ✅ 

The Table with the missing retirements from your screenshot is getting your retirements data via the Subgraph.

**Get the last 5 retirements of Jabby from Subgraph:**
- [Open QUERY](https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/graphql?query=query+MyQuery+%7B%0A++klimaRetires%28%0A++++first%3A+5%0A++++where%3A+%7BbeneficiaryAddress%3A+%220x6476edf98bdc5ee62f9d4e4bf8932d69ed685483%22%7D%0A++++orderBy%3A+timestamp%0A++++orderDirection%3A+desc%0A++%29+%7B%0A++++id%0A++++index%0A++++beneficiaryAddress%0A++++amount%0A++++retirementMessage%0A++++timestamp%0A++++offset+%7B%0A++++++vintage%0A++++++projectID%0A++++++name%0A++++%7D%0A++%7D%0A%7D) (and click on "play")
- Query as code in [Klimadao/lib](https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/subgraph/queryPolygonBridgedCarbon.ts#L70)
- **Result:** The latest retirements which have **NOT BEEN PAID** with Credit Card (last index is "22" and should be "28")
- **Result:** The retirements paid with Credit Card are missing 🐛 ❌

When rendering the final receipt of a retirement with credit card, the subgraph is queried too:

**Get the retirement of Jabby with index 28 (27) from Subgraph:**

- [Open QUERY](https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/graphql?query=query+MyQuery+%7B%0A++klimaRetires%28%0A++++where%3A+%7BbeneficiaryAddress%3A+%220x6476edf98bdc5ee62f9d4e4bf8932d69ed685483%22%2C+index%3A+27%7D%0A++++orderBy%3A+timestamp%0A++++orderDirection%3A+desc%0A++%29+%7B%0A++++id%0A++++index%0A++++beneficiaryAddress%0A++++amount%0A++++retirementMessage%0A++++timestamp%0A++++offset+%7B%0A++++++vintage%0A++++++projectID%0A++++++name%0A++++%7D%0A++%7D%0A%7D) (and click on "play", _Non-Dev-Note: Index is here 27 ! Because arrays start at "0"_)
- Query as Code in [Klimadao/lib](https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/subgraph/queryPolygonBridgedCarbon.ts#L5)
- **Result:** Not found 🐛 ❌
- **Result:** Retirement Receipt results in a 404

## Questions

- [ ] Did something change on the subgraph? During development last week the retirements have been queried successfully
- [ ] How come the contract gets the correct numbers for a beneficiary but the subgraph is missing only the ones via credit card payments (the ones where the beneficiary was not also the wallet address)?

**Comment by ladytrekker** [comment]
Closing as this was related to (now fixed) issue with the subgraph
