### ISSUE TITLE
[contract v2] Mumbai purchase activities are missing

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1680]
I made purchases from Shimon `0x6f9f81eb4f54512be8c91833783ee0074328e062` but they don't appear in the user.activities array for his wallet.

Note:
The purchase activity **does** appear in the project.activities array see [here](https://api.carbonmark.com/projects/VCS-981-2017?network=mumbai)

**Expected behavior**
If Jane buys from Bob, this query should show Janes purchases from bob in the Activities
(where $wallet is bob's wallet)
```
query getUserByWallet($wallet: Bytes, $expiresAfter: BigInt) {
  users(where: { id: $wallet }) {
    activities(orderBy: timeStamp, orderDirection: desc, first: 20) {
      ...ActivityFragment
    }
  }
}
```

https://api.thegraph.com/subgraphs/id/QmQZZSTzdP1JzyfvcZwJTZ6CCNXCBmhirc2AyCh4VDzPFV/graphql?query=fragment+ListingFragment+on+Listing+%7B%0A++id%0A++totalAmountToSell%0A++leftToSell%0A++tokenAddress%0A++active%0A++deleted%0A++singleUnitPrice%0A++createdAt%0A++updatedAt%0A++seller+%7B%0A++++id%0A++%7D%0A++project+%7B%0A++++...ProjectFragment%0A++%7D%0A++expiration%0A++minFillAmount%0A%7D%0A%0Afragment+ProjectFragment+on+Project+%7B%0A++id%0A++key%0A++vintage%0A++name%0A++category+%7B%0A++++id%0A++%7D%0A++country+%7B%0A++++id%0A++%7D%0A++methodology%0A%7D%0A%0Afragment+ActivityFragment+on+Activity+%7B%0A++id%0A++amount%0A++previousAmount%0A++price%0A++previousPrice%0A++timeStamp%0A++activityType%0A++project+%7B%0A++++key%0A++++vintage%0A++%7D%0A++buyer+%7B%0A++++id%0A++%7D%0A++seller+%7B%0A++++id%0A++%7D%0A%7D%0A%0A%0Aquery+getUserByWallet%28%24wallet%3A+Bytes%2C+%24expiresAfter%3A+BigInt%29+%7B%0A++users%28where%3A+%7B+id%3A+%24wallet+%7D%29+%7B%0A++++activities%28orderBy%3A+timeStamp%2C+orderDirection%3A+desc%29+%7B%0A++++++...ActivityFragment%0A++++%7D%0A++%7D%0A%7D%0A%23+0xab5b7b5849784279280188b556af3c179f31dc5b%0A%23+0x6f9f81eb4f54512be8c91833783ee0074328e062

**Comment by Atmosfearful** [comment]
This is a subgraph bug that impacts the frontend so I'm posting here instead of the subgraphs repo.

**Comment by cujowolf** [comment]
Taking the full query from the api, it could be modified to not route through the `User` entity since that is linked to the address that originates the transaction. 

```graphql
query getUserByWallet($wallet: Bytes, $expiresAfter: BigInt) {
  listings(where: {seller: $wallet, expiration_gt: $expiresAfter}) {
    ...ListingFragment
  }
  activities(
    orderBy: timeStamp
    orderDirection: desc
    first: 10
    where: {or: [{seller: $wallet, activityType_not: Purchase}, {buyer: $wallet}]}
  ) {
    ...ActivityFragment
  }
}
```

The above query allows for pulling all listings by the seller after a defined expiration timestamp, along with any seller activities other than `Purchase` which should only display for the buyer.

https://api.thegraph.com/subgraphs/id/QmQZZSTzdP1JzyfvcZwJTZ6CCNXCBmhirc2AyCh4VDzPFV/graphql?query=fragment+ListingFragment+on+Listing+%7B%0A++id%0A++totalAmountToSell%0A++leftToSell%0A++tokenAddress%0A++active%0A++deleted%0A++singleUnitPrice%0A++createdAt%0A++updatedAt%0A++seller+%7B%0A++++id%0A++%7D%0A++project+%7B%0A++++...ProjectFragment%0A++%7D%0A++expiration%0A++minFillAmount%0A%7D%0A%0Afragment+ProjectFragment+on+Project+%7B%0A++id%0A++key%0A++vintage%0A++name%0A++category+%7B%0A++++id%0A++%7D%0A++country+%7B%0A++++id%0A++%7D%0A++methodology%0A%7D%0A%0Afragment+ActivityFragment+on+Activity+%7B%0A++id%0A++amount%0A++previousAmount%0A++price%0A++previousPrice%0A++timeStamp%0A++activityType%0A++project+%7B%0A++++key%0A++++vintage%0A++%7D%0A++buyer+%7B%0A++++id%0A++%7D%0A++seller+%7B%0A++++id%0A++%7D%0A%7D%0A%0Aquery+getUserByWallet%28%24wallet%3A+Bytes%2C+%24expiresAfter%3A+BigInt%29+%7B%0A++listings%28where%3A+%7Bseller%3A+%24wallet%2C+expiration_gt%3A+%24expiresAfter%7D%29+%7B%0A++++...ListingFragment%0A++%7D%0A++activities%28%0A++++orderBy%3A+timeStamp%0A++++orderDirection%3A+desc%0A++++first%3A+10%0A++++where%3A+%7Bor%3A+%5B%7Bseller%3A+%24wallet%2C+activityType_not%3A+Purchase%7D%2C+%7Bbuyer%3A+%24wallet%7D%5D%7D%0A++%29+%7B%0A++++...ActivityFragment%0A++%7D%0A%7D
