### ISSUE TITLE
[klima data] Left nav loses focus when on a Details page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1739]
Page: all detail pages

Issue:
- When I open a Details page, the left nav loses focus of the primary page
- For example

![image](https://github.com/KlimaDAO/klimadao/assets/103535195/9e2c3b7a-4409-4abc-abe1-ab019a9245cd)

**Comment by sprrwhwk** [comment]
@biwano are you aware of any two top-level pages linking to the same detail page?
If not then I would restructure the project files and move all detail pages under a single parent page. That would make active path handling a lot easier (change useIsPathnameActive to startsWith instead of ==).

An alternative would be to use a context hook to set the active parent page but it seems hacky and it will be complicated if a detail page can have two parents (What link should be active if we have multiple parents? The one where we came from?).

**Comment by biwano** [comment]
> @biwano are you aware of any two top-level pages linking to the same detail page? If not then I would restructure the project files and move all detail pages under a single parent page. That would make active path handling a lot easier (change useIsPathnameActive to startsWith instead of ==).
> 
> An alternative would be to use a context hook to set the active parent page but it seems hacky and it will be complicated if a detail page can have two parents (What link should be active if we have multiple parents? The one where we came from?).

The tokenized credits by bridge is both on the detail page and the off vs on page. I like your idea though. We could duplicate the tokenized credits by bridge detail page to make it work. But I do not know if it is a good idea SEO wise.
Let me tag @Atmosfearful too.
