### ISSUE TITLE
[klima data] Retirement trends - by chain | Update chart based on new design

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1757]
This page: https://carbon-git-staging-klimadao.vercel.app/retirement-trends?tab=byChain
Also this details page: https://carbon-git-staging-klimadao.vercel.app/details/retirement-trends-by-chain

This component:
<img width="771" alt="Screenshot 2023-10-25 at 10 40 43 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ae27fb1c-2248-4104-9122-b5da63b58a15">

Issue:
- need a visual that allows us to differentiate between on-chain vs off-chain given that KlimaDAO retirements off chain are very small

**Comment by theprofessora** [comment]
Let's go with the synchronized line chart outlined here: https://recharts.org/en-US/examples/SynchronizedLineChart

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/e793fcec-3cad-4bca-b9b8-846985919d9d)

Essentially, we show off-chain retirements and on-chain retirements side-by-side. the Recharts Synchronized Line Chart will allow us to hover over one spot on either graph and the same X-Axis value will be hilighted by a tooltip on both graphs

we can also assign a different y-axis scale to each graph so that we can zoom in on the parts of each graph that actually show change (the top end of the off-chain graph and bottom end of the on-chain graph).

These two graphs side by side should be exact opposites of one another, as when the off-chain retirements % drops by a point or two, the on-chain retirements % will increase by that exact amount.

**Comment by jabby09** [comment]
@biwano @sprrwhwk 

[updated design here](https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?type=design&node-id=2787-11224&mode=design&t=0Dm4un6wlQewqRUY-4)
[details page](https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?type=design&node-id=2787-11306&mode=design&t=0Dm4un6wlQewqRUY-4)
