### ISSUE TITLE
[demo] MVP design enhancements

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1903]
MVP link https://carbonmark-git-emc-feature1823-demo-package-klimadao.vercel.app/retirement-demo

Design review and suggestions to improve. 
If dev time permits, what else could we add to the page.

Note..we only have 1 week remaining of dev time so any design feedback needs to be simple to implement.

**Comment by 0xtapi** [comment]
Few ideas for this section:
![Screenshot 2023-11-17 103350](https://github.com/KlimaDAO/klimadao/assets/128430614/5f7dd81b-443a-4657-9899-27e33d149747)

1. What about making the small battery symbol next to "Renewable Energy" Klima green (or leave the battery, but make the background of that element green)? Right now, the site is very gray on gray with a touch of gray. Some color might be cool.

2. Is the selection of credits a placeholder? If not, we could offer a wider selection, like the cheapest credit we have, the cheapest nature-based credit, and top tier credits (Mangrove's listing?).

On a more general note: The site currently uses "Offset" as the term to retire carbon. On Carbonmark, we always call it retire. I recall Marcus mentioning we should steer away from "Offset" because of negative connotations. Maybe replace some of the wording, e.g. turn "Offset the emissions generated..." into "Compensate for the emissions generated...". Label the buttons "Compensate" maybe? "Retire" could be a bit technical... 

Not too sure about the best path here, but "Offset" might not be the optimal solution.

**Comment by jabby09** [comment]
> 1. What about making the small battery symbol next to "Renewable Energy" Klima green (or leave the battery, but make the background of that element green)? Right now, the site is very gray on gray with a touch of gray. Some color might be cool.

Overall this page should match Carbonmark branding, no Klima green should be in the demo app. The cards I believe will match the CM marketplace cards.

**Comment by jabby09** [comment]
> 2\. Is the selection of credits a placeholder? If not, we could offer a wider selection, like the cheapest credit we have, the cheapest nature-based credit, and top tier credits (Mangrove's listing?).

Yes these are placeholder. The actual projects/credits will be from EcoRegistry but that is still being worked on.

**Comment by jabby09** [comment]
> The site currently uses "Offset" as the term to retire carbon

Yes agree, this is all placeholder content. Will need a review from marketing and the content term but overall agree should avoid use of work Offset.

**Comment by theprofessora** [comment]
Here are my thoughts:

1. on shorter computer screens, the top logo is cut off. Let's add some padding to the top of the page
2. let's add in the carbonmark landing page header so people can check us out if they want
3. the map component stretches all the way across the page, making it very difficult to scroll using the mousewheel because on most of the page, scrolling the mousewheel just zooms the map instead of scrolling the page.
4. Let's put all the content on a card so we can contain all the form actions to one central location (using the drop downs and interacting with the map). this also makes the page look a little more organized
5. on the desktop version, let's add in a big, but very faint, watermark so we have some visual intricacy

you can see my edits here: https://www.figma.com/file/xvIkQnzm55XPvxYgxobssN/COP-Quick-Offset-Tool?type=design&node-id=1-3&mode=design

**Comment by jabby09** [comment]
@Atmosfearful see professors suggestions and design file above.
Leaving this now with you to action as required.

**Comment by 0xemc** [comment]
> Here are my thoughts:
> 
> 1. on shorter computer screens, the top logo is cut off. Let's add some padding to the top of the page
> 2. let's add in the carbonmark landing page header so people can check us out if they want
> 3. let's add in an `h1`
> 4. the map component stretches all the way across the page, making it very difficult to scroll using the mousewheel because on most of the page, scrolling the mousewheel just zooms the map instead of scrolling the page.
> 5. Let's put all the content on a card so we can contain all the form actions to one central location (using the drop downs and interacting with the map). this also makes the page look a little more organized
> 6. on the desktop version, let's add in a big, but very faint, watermark so we have some visual intricacy
> 
> you can see my edits here: https://www.figma.com/file/xvIkQnzm55XPvxYgxobssN/COP-Quick-Offset-Tool?type=design&node-id=1-3&mode=design

Some additional context for this one, the demo is intended to be shown on an Ipad/tablet during the COP summit so keep that in mind in regards to the user visiting carbonmark itself and layout stuff  (mouse scrolling etc)
