### ISSUE TITLE
[retirement] Confirm retirement receipt info has fallback to on-chain data

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1918]
Research / code check.

On retirement receipts, for example https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/31

- [x] Confirm that the information has fallbacks to on-chain data.

**Comment by biwano** [comment]
Hi @jabby09. 
Can you be a bit more specific?
Is the goal is to be able to render the page even if the retirement pertains to a project that does not exist in the carbonmark database?

**Comment by jabby09** [comment]
> Can you be a bit more specific?
> Is the goal is to be able to render the page even if the retirement pertains to a project that does not exist in the carbonmark database?

This was an ask from @Atmosfearful so I think you will need to sync up with him and confirm the requirements.
My understanding was that atmos wanted to confirm that in the retirement receipt code we had fallbacks in the case where we could not read the project data from the CMS.

**Comment by biwano** [comment]
@jabby09 @Atmosfearful 
So, the code already contains the logic for fallback data but it does not work because of the change where the http client throws errors when the request fails.
I made a PR to address that https://github.com/KlimaDAO/klimadao/pull/1923
It contains also a little improvement: it prevents the description label to be displayed when there is no description available.
