### ISSUE TITLE
[receipt] MC02 retirement receipts resulting in 404 page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1927]
Use this wallet as an example: https://www.carbonmark.com/retirements/0xbcd65097034d637ac49236e3514fd1aadf3f5d58

Click any of the MC02 retirements and result is 404 page.

Example https://www.carbonmark.com/retirements/0xbcd65097034d637ac49236e3514fd1aadf3f5d58/10

**Comment by 0xMakka** [comment]
@jabby09 / @Atmosfearful / @0xemc  I done some investigation around this. It looks like for MCO2 retirements, the data pulled from subgraph isn't including the ProjectID field for MCO2, but not sure if this is expected, as I remember working on the retirement pages and MCO2 details were handled differently. See screenshots below of a comparison of the data returned for a BCT retirement vs a MCO2 retirement.

<img width="1512" alt="Screenshot 2023-11-25 at 00 01 35" src="https://github.com/KlimaDAO/klimadao/assets/92357475/5537f51c-040d-43e8-989e-b38af0f59a6c">

When running this locally, I can reproduce the issue. The following error is thrown, it looks like on the api it's expecting a projectID starting with `VCS|PURO|ICR|GS`. My assumption is because the projectID is empty from the subgraph data -  the error is thrown and as a result the 404 page is rendered. 

<img width="984" alt="Screenshot 2023-11-25 at 00 02 01" src="https://github.com/KlimaDAO/klimadao/assets/92357475/03b09fd6-732a-47b7-80d3-eca36aa47e2b">

**Comment by 0xemc** [comment]
@cujowolf looks like we need the `projectID` and the `vintageYear` in order for the api to fetch the project data.

```ts
    const project = await getProjectsId(
      `${retirement.offset.projectID}-${retirement.offset.vintageYear}`
    );
```

Any chance you could take a look at if this data is available for MC02 tokens?
