### ISSUE TITLE
[ICR] ICR credit transfer to CM connected wallet

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#1978]
There is currently no implementation of a user friendly way to transfer ICR credits over to a CM connected wallet.

ICR currently has enabled this feature, but discovery is needed for the exact requirements of implementing.

For a high-level flow/understanding-->

1. We will create a Carbonmark 'app' (ICR has documentation for this) that users can install on their organization on ICR's platform.
2. On Carbonmark, because the Carbonmark app is installed on ICR we can then retrieve the user's ICR holdings. 
3. From Carbonmark, the user will request X amount of Y credits to move to their CM wallet. 
4. Currently they then have to approve this request on ICR, but ideally we can handle the approval through the api as well.

**Comment by jabby09** [comment]
Call notes summary from meeting between Peter and Brendan

**The migration to CM wallets is somewhat of a blocker for ICR import/export oauth:**  

1) on the user side where users would have to recreate the oauth connection with their new CM wallet
 
2) on the development side where the api code would need to be refactored to use the Team / User Ids vs current EOAs

**The much lower lift interim solution to import credits into CM:**

Project developers who want to transfer their credits to CM will transfer their credits to the Carbonmark ICR organization (this is currently enabled in the ICR's organization UI). 

We will create a password protected internal tool in the new private CM repo that  facilitates transfers from the CM org to a CM EOA. The API Key will be in an env, so only the destination address, project, and amount are needed to transfer the credits. Once the credits are in the developer's specified EOA they can interact with Carbonmark in all the usual ways.

**Export Dapp:**

The above does not support export. In order to support export we need ICR to enable an endpoint that exposes an organization's destination address from their org Id (this conversation is ongoing). 

Once we have this endpoint we can create a mini-dapp that takes in the org id, queries the endpoint, retrieves the address and sends back the credits to the org address. This export dapp can be public as they will be signing the export transaction with their wallet.

Stretch goal: attach luckyOrange events so we can see which users use the export tool.

**Comment by Atmosfearful** [comment]
Done! Nice work @psparacino 💯  💯  💯  💯
