### ISSUE TITLE
Order status linked to blockchain events

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2330]
There is a need to sync the status of supabase database entries for orders to the current state of transactions in the polygon network. This should be implemented in a single instance using webhooks that listen to on-chain events. For reference [https://moralis.io/polygon-webhooks-how-to-use-webhooks-on-polygon/](https://moralis.io/polygon-webhooks-how-to-use-webhooks-on-polygon/)

Relates to:

[https://github.com/Carbonmark/monorepo/issues/146](https://github.com/Carbonmark/monorepo/issues/146) [https://github.com/Carbonmark/monorepo/issues/146](https://github.com/Carbonmark/monorepo/issues/146)

**Comment by Atmosfearful** [comment]
We have a separate Bet for webhook support (customer-facing, which implies that we implement realtime transaction listening for ourselves too) so I'll keep this closed and track ideas in that bet.

This is a slippery slope though because we are using serverless functions which are better suited for idempotent requests, so I don't want to prioritize this yet
