### ISSUE TITLE
Simplify translation process

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2331]
The current translation process is overly complex and prone to bleeding bugs in to production. We need a simpler solution that everyone can understand and that exposes issues before they get to production.

**Comment by Atmosfearful** [comment]
Sorry to be blunt but "I don't understand the translation process" is not ticket worthy...

If you can pinpoint where the problem is or where bugs are being introduced, or make a case for an alternative that would be a start. Here is how the process works:
- strings are tagged with the lingui macros
- `extract`:  lingui parses the source code and outputs source strings to a locales/en file
- On every commit to staging we run extract and sync it to the translation service (pulls new translations, pushes source changes)
- `compile`: before builds (postinstall) we run this command to convert the string source files into useable JSON. This json is not commited to git
- Source locale file for the chosen language is loaded on server (or during static build) and passed as prop
- Lingui consumes this in a provider in _app.tsx

We settled on this process because it is completely automated and avoids the need for "string freeze" like some teams do.

## Known issues
My only gripes have been with Lingui being tied to Babel (preventing us from using faster Nextjs tooling)
And some breaking changes they introduced with their new version
And of course the billing mistake which was because legal canceled our card and I forgot to update it.

**Comment by Atmosfearful** [comment]
Will be moved to CM repo
