### ISSUE TITLE
[tech debt] Better developer experience for lingui string ids?

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#279]
Common issues I'm noticing:
1. Accidentally copy-paste a string id for a new element, end up reusing the wrong text in your UI.
    -  If you haven't extracted strings, you won't notice it in local preview mode (which is using fallback text), could easily end up on prod
2.  Simply forgetting to extract strings before opening a PR. The dev env is deceiving.
    - We can discuss using a Git Commit hook, or a github action to resolve this.
4. Change the inner text, forget to update the .po file. Not sure if this is an actual issue: @biwano Does simply running `extract-strings` update the en.po with a new source string? Or do you need to go in and edit the .po manually?

Any way we can avoid these issues or catch them before they get to prod? Does lingui have any tooling to catch duplicates?

Maybe we need to migrate to a system where only common, reused strings and very stable strings are given IDs, and everything else uses the auto-generated id from lingui?

**Comment by Atmosfearful** [comment]
Just opening for discussion, let's get in sync before we rework anything @biwano

**Comment by Atmosfearful** [comment]
https://github.com/KlimaDAO/klimadao/pull/278#discussion_r836975070

**Comment by biwano** [comment]
This should not be a problem. 
From what I remember, if you have two tags  with the same ids but different source text. `lingu :extract` fails. So the PR would not pass checks. 
I will check again to make sure.

**Comment by biwano** [comment]
To follow up here are the tests results:
```[biwano@localhost site]$ npm run lingui:extract

> lingui:extract
> NODE_ENV=test lingui extract --clean

Cannot process file /home/biwano/code/klimadao/site/components/pages/Resources/Community/index.tsx: Different defaults for the same message ID.
  89 |           <Text t="h5" align="center">
  90 |             <Trans id="community.lets_work_together">Let's Work Together</Trans>
> 91 |             <Trans id="community.lets_work_together">Let's Work aa</Trans>
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  92 |           </Text>
  93 |           <Text t="h2" as="h2" align="center">
  94 |             <Trans id="community.become_a_partner">BECOME A PARTNER</Trans>
Catalog statistics for /home/biwano/code/klimadao/site/locale/{locale}/messages: 
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │     94      │    -    │
│ fr          │     94      │   29    │
│ en-pseudo   │     94      │   93    │
└─────────────┴─────────────┴─────────┘

(use "npm run lingui:extract" to update catalogs with new messages)
(use "npm run lingui:compile" to compile catalogs for production)
[biwano@localhost site]$ echo $?
0
```

As you can see `lingui extract` identifies the issue BUT the return value is 0.
One way to solve this problem could be to wrap the `lingui extract` command to check for such an issue and return a non 0 value in this case.

**Comment by biwano** [comment]
@Atmosfearful I am not sure on the process to close tickets at KlimaDAO. (Is it the person that opens it that has to close it so they can have a final look?).
So I close it saying it is fixed by https://github.com/KlimaDAO/klimadao/pull/285 and if need be we can reopen.

**Comment by ladytrekker** [comment]
@biwano @Atmosfearful 

I just noticed that since the [merge of this PR](https://github.com/KlimaDAO/klimadao/pull/285) the script behaves differently:
Before the statistics have been logged when running `npm run extract-strings` locally. 
Now not anymore.

Also on github actions which runs `npm run compile-strings` on the server the logs says: `sh: 1: [[: not found`
https://github.com/KlimaDAO/klimadao/runs/5820254529?check_suite_focus=true
=> click on/open step "Extract and Compile Translation strings"

See here a run with the nice formatted output before the merge of this PR
https://github.com/KlimaDAO/klimadao/runs/5756588447?check_suite_focus=true
=> click on/open step "Extract and Compile Translation strings"

Still the script seems to work correctly from my point of view.
At least the new translations have been pulled from translation.io on each run.

Just want to make sure that this is intended. 🙂 
**What do you think?**


**Before:** Nice formatted results with statistics when running `npm run extract-strings`

![Bildschirmfoto 2022-04-04 um 15 29 18](https://user-images.githubusercontent.com/95881624/161624340-df28d2e4-69f1-41e8-b4fd-fd156043c6ab.png)

**After:** No logs
![Bildschirmfoto 2022-04-04 um 15 30 05](https://user-images.githubusercontent.com/95881624/161624430-35a773ae-1541-4d49-9c81-5a57c3b0b30b.png)
