### ISSUE TITLE
Support locale query parameter in the dApp

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#322]
* [x] Consume & strip the param when the top level component mounts. See how I did it here: https://github.com/KlimaDAO/klimadao/blob/staging/app/lib/hooks/useOffsetParams.ts#L47
* [x] all links from site to dapp should pass the current locale as param

**Comment by Atmosfearful** [comment]
Here is where we set the locale in redux state
https://github.com/KlimaDAO/klimadao/blob/staging/app/components/views/Home/index.tsx#L160

**Comment by ladytrekker** [comment]
It is a bit more complex:

## Problem
- The site is a different domain, this is different from the mentioned params hook mentioned above.
- We can check the Referer URL of the HTTP request, but even when a language was chosen on site => the Referer URL does not include the language tag 
=> **referer**: `https://staging-site.klimadao.finance/` instead of **referer**: `https://staging-site.klimadao.finance/de`

## Solution

We rather need to check the `window.navigator.language` of the current browser instead.
But this would mean that even if a user selected e.g. french on Site but the browser/client language is german
=> The app would set German to the state.

I think this is ok.

**Comment by Atmosfearful** [comment]
Just so we are on the same page, the _ideal_ behavior I'm imagining is this:
### when navigating directly to the `app`
1. Use the language indicated in the url `?locale=de`
1. Otherwise use most recently selected language (localstorage)
1. fallback to browser language
1. fallback to EN

### When navigating directly to the site
1. Use the language indicated in the URL e.g. `/de`
1. Use previously selected language
1. Check browser language

### When navigating from `site->app`
pass query param `?locale=de`

### When navigating from `app->site`
pass locale path `/de`
