### ISSUE TITLE
.klima domain and ENS domain name integration

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#362]
Designs needed!

Requirements:
In the dapp, when a user connects their wallet, we can show their .klima profile and domain.
If they don't have a .klima, show their ENS.
If they don't have ENS, show the public address (current implementation)

Other considerations:
- Should we still show the public address somewhere?
- What if they have an ENS or Klima domain, but no profile pic?

**Comment by tempe-techie** [comment]
- `.klima` contract address on Polygon: `0xe8b97542A433e7eCc7bB791872af04DF02A1a6E4`
- in order to get user's `.klima` name (reverse-lookup), call the `defaultNames` method: `defaultNames(address)`
- if user holds multiple domain names and wants to change their default name, they can call this function: `editDefaultDomain(domainName)` (note that only name is added here without TLD, so if domain is `timmy.klima`, only enter `timmy` as the input)
- in order to check which address holds a certain domain name (lookup), call this method: `getDomainHolder(domainName)`

Let me know if you'll have any questions 🙂
