### ISSUE TITLE
Improve UX when wallet is not connected

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#408]
When the wallet is not connected, the user cannot use the functions (stake, bond etc...). Buttons are deactivated.
But there is a possibility for the average user to not understand why they cannot use the app.

We could add a message to make things more explicit.

Let me know if it makes sense.

**Comment by Atmosfearful** [comment]
I think we should do a big design jam on this. It would lead to a fundamental restructuring of the app. I've mentioned this to a few people. But I keep punting it aside because it's going to be a lot of work...
1. blocking access to the dapp completely when not connected with a "please connect on polygon" view. See toucan.earth for an example
2. After they are connected, having top-level loading spinner, or maybe a loading state for each view until all the relevant balances/allowances are loaded-- similar to how the driver app did it

We definitely need designs on this.

**Comment by jabby09** [comment]
Deprecated by Carbonmark. Generally web3 savy users will be the only group using the dApp soon.
