### ISSUE TITLE
Fix twitter cards for blog posts

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#448]
Perhaps we aren't passing the correct image URLs down...

**Comment by biwano** [comment]
Hi @Atmosfearful !

Everything seems fine on the site side.
for instance, in page `https://www.klimadao.finance/fr/blog/response-to-verra-comments-on-crypto-instruments-and-tokens`
The meta for twitter:image is `<meta name="twitter:image" content="https://cdn.sanity.io/images/dk34t4vc/production/79d1b9b219d6feaa6eefa89b2e0a7c43d9ee4d9c-4312x2160.png"/>`
The image at address `https://cdn.sanity.io/images/dk34t4vc/production/79d1b9b219d6feaa6eefa89b2e0a7c43d9ee4d9c-4312x2160.png` seems okay.

Can you send me the link to the twitter post? Maybe there is a particular problem with (a) particular post(s).

**Comment by biwano** [comment]
I think I found it after re-reading the docs: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

There are specifications for image size, notably: `maximum of 4096x4096 pixels. Images must be less than 5MB in size.`
The image in the post I checked is 4312x2160 and a wooping 7MB.

The problem must come from that.

**Comment by biwano** [comment]
@Atmosfearful Do you think we can try to resize the image in one of the problematic posts to see if it really comes from that?

**Comment by Atmosfearful** [comment]
@biwano I DM'd you on discord about this, I'll give you CMS access.

**Comment by biwano** [comment]
@Atmosfearful Progress so far: I put the same image on this blog `https://staging-site.klimadao.finance/blog/klima-dao-fair-launch-pt-1-initial-discord-offering` that is on the home page. And it still does not work. Here are my thoughts:
- There may be a cache issue on the twitter side (which I doubt).
- Something really is wrong in the meta tags.
- Something is wrong with the way the CDN delivers the images.

I keep investigating

**Comment by biwano** [comment]
@Atmosfearful 

# Root cause analysis

There was indeed a cache on the tweeter side. I had to change the blog slugs to progress.
You can check those tweets:
- Image respects twitter specs: https://twitter.com/biwa73847927/status/1536067000665001984?s=20&t=PYzzVDgpCK8qPckeMy98Mg => Tweet is beautiful
- Image does not respect twitter specs: https://twitter.com/biwa73847927/status/1536066091830607880?s=20&t=PYzzVDgpCK8qPckeMy98Mg => Tweet is ugly

So the root cause seems that it is just a matter of the blog images not respecting twitter specs.

# Solutions
## For Previous blog posts
Case 1:  Tweeter caches the images forever

The previous blog posts can be rescued if we change their slugs, resize the images and republish. The problem is that the links previously posted on the internet will render a 404 error.

Case 2: Tweeter caches expires

The previous blog posts can be rescued if we resize the images and republish. We just have to have more patience than twitter cache expiry system.
We can check if the cache expires by updating one of the blog which has the issue with a compliant image and see when/if the corresponding twitter post starts looking good.

## For future blog posts

In order of preference

- The CDN Klima uses seems to have on the fly resize capabilities: https://www.sanity.io/docs/image-urls I will investigate if we can modify the urls for og tags so they fetch lower quality versions
- Ask the content managers to upload images compliant with tweeter specs

**Comment by biwano** [comment]
#482 should solve this.
