### ISSUE TITLE
[research] Add error logging to the frontend

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#687]
- first for smart contract interactions
- then for next api endpoints
- then for other core user journeys
- maybe a top level catch-all for the whole site / app (if it's not too noisy)

I am aware of bugsnag, sentry.io... what is the industry standard?
- must be lightweight, perhaps even wrapped in a next /api/ endpoint so that we don't add anything to our js bundle.
- how does pricing work?

**Comment by biwano** [comment]
Little market study.
![image](https://user-images.githubusercontent.com/11857992/206701725-9223f147-ab03-4d8b-a6d9-ea02b5cfeb7f.png)

**Comment by biwano** [comment]
A quick read of the tools documentation show that they all offer the basic features we would need: 
- Javascript error logging (catch unhandled exceptions)
- Performance monitoring

Most of them generate Breadcrumbs (Pieces of information that are added to the error report - eg. user interractions prior to the crash -) and enable developpers to add custom breadcrumbs

Some of them have a feature called session replay. This works by logging timestamped snapshots of the DOM to the server when it changes. Those snapshots can be replayed later. (eg. https://sentry.io/for/session-replay/ )

I Highlighted 3 platforms which provide all these features: Sentry, LogRocket and DataLog.
In regard with the KlimaDAO project, Sentry has an edge because it offers a native NextJS SDK and support for Vercel which can enable end to end performance profiling.
