### ISSUE TITLE
[buy] Extra space on page, CSS change

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#962]
from a community member...léo#4643
related to error on buy page https://app.klimadao.finance/#/redeem

> Cool thanks 🙂 not sure if it is related, there are now 4 rows in the grid template css, creating an extra space at the bottom of the page where the rogue button used to be. The space can be removedby switching the CSS property from grid-template-rows: min-content 1fr 1fr 1fr; to grid-template-rows: min-content 1fr;
> 
> And also, my browser logs a couple of CORS errors on that page (Firefox 111.0.1, Ubuntu 22.04)

![Image](https://user-images.githubusercontent.com/103535195/228864604-6ec00097-16c0-45fd-b46f-7d7a1552bdc9.png)

**Comment by jabby09** [comment]
@biwano I noticed you have a comment on this one...is there something to pick up on for this issue or can it be closed?

**Comment by biwano** [comment]
Hi @jabby09 

- [X] The redeem page content was replaced by a CTA in this PR: https://github.com/KlimaDAO/klimadao/pull/1908
- [X] The same origin issues should be solved: I cannot reproduce the issue and I checked that the Access-Control-Headers are correct: 
![image](https://github.com/KlimaDAO/klimadao/assets/11857992/338b976d-9752-4ccd-b89f-81c25a2d92a9)
- [X] I noticed the issue with the React 418 when doing this PR: https://github.com/KlimaDAO/klimadao/pull/1908 and I think I solved it there. 

There is another React 418 error due to how the lingui framework is integrated but I do not think we can solve it easily.

**Comment by jabby09** [comment]
thanks @biwano for the update
So do you think this issue can be closed?

**Comment by biwano** [comment]
> thanks @biwano for the update So do you think this issue can be closed?

Yes I think we can.
